name: go-modules-action
description: Get modules contained in the repository (./, pkg)

inputs:
  dir:
    description: Directory
    required: false

outputs:
  modules:
    description: 'JSON string from modules list'

branding:
  icon: 'list'
  color: 'orange'
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - '${{ inputs.dir }}'
